
include: "rules/common.smk"
include: "rules/ascp_ccs.smk"
include: "rules/ascp_ccs_md5.smk"
include: "rules/edit_md5.smk"
include: "rules/md5dum_check_ccs.smk"
include: "rules/seqkit.smk"
include: "rules/zcat_ccs.smk"
include: "rules/jellyfish_count_ccs.smk"
include: "rules/gunzip_hifi.smk"
include: "rules/gunzip_chromosome.smk"
include: "rules/jellyfish_count_hifi.smk"
include: "rules/jellyfish_count_chromsome.smk"
include: "rules/kat_hifi.smk"
include: "rules/kat_chromsome.smk"

rule all:
    input:
        expand(
            "results/seqkit_stats/{sample}.tsv",
            sample=sample_data.index.tolist(),
        ),
        expand(
            "results/md5sum_check/{sample}.txt",
            sample=sample_data.index.tolist(),
        ),
        "results/kat_hifi/kat-main.mx.spectra-cn.png",
        "results/kat_chromosome/kat-main.mx.spectra-cn.png",

